name: 云服务器CICD
# 监听 main
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    # 构建环境使用 ubuntu
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write

    steps:
      - name: 检出代码
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 设置Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16
          cache: npm

      - name: 设置Pages
        uses: actions/configure-pages@v4

      - name: 安装依赖
        run: npm install --legacy-peer-deps

      - name: 构建dist
        run: npm run build:prod

      - name: 设置 Cloudflare Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: 发布到 Cloudflare Pages
        id: cloudflare_pages
        continue-on-error: true
        uses: cloudflare/wrangler-action@v4
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          command: pages deploy dist --project-name=lucky-admin-vue --branch=main

      # 清空目标服务器上的目录内容
      - name: 清空目标服务器该文件夹下内容
        if: ${{ steps.cloudflare_pages.outcome != 'success' }}
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            rm -rf /nwa/nginx/html/admin/*

      # 部署到服务器
      - name: 上传打包后的资源到服务器
        if: ${{ steps.cloudflare_pages.outcome != 'success' }}
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          source: './dist/*'
          target: '/nwa/nginx/html/admin'
          strip_components: 1
